// Quick test to verify the INSERT+subquery formatting
const { formatSql } = require('../src/lib/sqlFormatter');

const sql = `INSERT /*+ APPEND */ INTO WK_DT_TOKUBAI_GENKA ( TENPO_CD, SYOHIN_CD, SIIRESAKI_CD, THEME_CD, GENKA_VL, HACHU_TN, TOKUBAI_KB ) SELECT HANSOKU2.TENPO_CD AS TENPO_CD, HANSOKU2.SYOHIN_CD AS SYOHIN_CD, HANSOKU2.SIIRESAKI_CD AS SIIRESAKI_CD, HANSOKU2.THEME_CD AS THEME_CD, HANSOKU2.GENKA_VL AS GENKA_VL, HANSOKU2.HACHU_TN AS HACHU_TN, HANSOKU2.TOKUBAI_KB AS TOKUBAI_KB FROM DT_HANSOKU HANSOKU2 WHERE HANSOKU2.%%PHYSLOC%% IN ( SELECT V2.ID FROM ( SELECT HANSOKU1.%%PHYSLOC%% AS ID, rank() over ( partition by TENPO_CD, SYOHIN_CD ORDER BY GENKA_VL, TOROKU_NB DESC ) AS RANKING FROM DT_HANSOKU HANSOKU1 WHERE kijunDt BETWEEN HANSOKU1.HANBAI_START_DT AND HANSOKU1.HANBAI_END_DT AND HANSOKU1.HANSOKU_KB IN ( mst000101_ConstDictionary.TIRASI, mst000101_ConstDictionary.SUPOTTO_TOKUBAI_RENDO, mst000101_ConstDictionary.SUPOTTO_TOKUBAI_HI_RENDO, mst000101_ConstDictionary.EDLP ) AND HANSOKU1.GENKA_VL IS NOT NULL AND HANSOKU1.DELETE_FG = '0' ) V2 WHERE V2.RANKING = '1' )`;

const res = formatSql(sql);
console.log(res.result);
